### PR TITLE
build: add API 55 with FlowTest

### PR DESCRIPTION
**Pull request by jdkgabri**
## What does this pull request contain?

This pull request contains the ` v55.json` file under the `metadata` folder, which is similar to `v54.json` but containing as well support for the new `FlowTest` metadata type.

---

- [x] Added (for new features).
- [ ] Changed (for changes in existing functionality).
- [ ] Deprecated (for soon-to-be removed features).
- [ ] Removed (for now removed features).
- [ ] Fixed (for any bug fixes).
- [ ] Security (for vulnerability fixes).

## Explain your changes

---

This Pull Requests aims to add support in order detect and include added/modified Flow Tests (included in Summer '22) in the result `package.xml`.

## Does this close any currently open issues? 
No.

---

- [ ] Jest test added to check the fix is applied.

## Any particular element that can be tested locally

The inclusion of the FlowTest elements in the output file package.xml when they are detected as added/modified by the command usage.

---

## Any other comments

---

## Where has this been tested?

---

**Operating System:**  Windows 11

**yarn version:** 1.22.17

**node version:** v16.13.0

**git version:** 2.33.1.windows.1

**sfdx version:** sfdx-cli/7.160.0 win32-x64 node-v16.16.0

**sgd plugin version:** 5.3.0

### CODE REVIEW

**Review by scolladon — APPROVED** [review]
LGTM

I checked using the documentation for [FlowTest](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_flowtest.htm).

Nice addition, thank you very much @jdkgabri !

**Review by scolladon — CHANGES_REQUESTED** [review]
Sorry I went too fast...

Could you revamp this PR so you can use the `increment:apiversion` npm script we have ?

Operation Manual:

1. Remove the v55.json file
2. Use `increment:apiversion`
3. commit the changed files and the new v55.json (enforce the [commit convention](https://github.com/conventional-changelog/commitlint#what-is-commitlint))
4. Add FlowTest in the v55.json
5. commit the addition

**Comment by jdkgabri** [comment]
Apologies, I have been struggling to get the required Linux tools in my Windows local machine (aside from `jq `and `sponge`, I was missing as well `tonumber`, `tostring `or `filename `for instance). I have read the `increment:apiversion` script and tried to manually apply the changes that I understood the script was doing. Besides I changed the commits and ordered them as you requested trying to follow the commit conventions.

**Review by scolladon — APPROVED** [review]
LGTM

Thanks for taking in account my previous feedback.
Sorry if I'm a little bit picky but it really helps to maintain the plugin later on.
Very nice job here, thank you very much @jdkgabri

**Comment by scolladon** [comment]
Version 5.3.1 just released with this PR !
Thanks @jdkgabri for this nice addition

**Pull request merged**
