### PR TITLE
feat: add `ExternalCredentials` metadata and `v56` api version

### PR DESCRIPTION
**Pull request by nodex0**
## What does this pull request contain?
This Pull Request contains an additional metadata definition for the ExternalCredentials and the additional v56 API version metadata.

---

- [x] Added (for new features).
- [x] Changed (for changes in existing functionality).
- [ ] Deprecated (for soon-to-be removed features).
- [ ] Removed (for now removed features).
- [ ] Fixed (for any bug fixes).
- [ ] Security (for vulnerability fixes).

## Explain your changes

---

Changed the v55.json to include the new ExternalCredentials and cloned it to create the v56.json for the new API version.

- [ ] Jest test added to check the fix is applied.

## Any particular element that can be tested locally

---

## Any other comments

---

## Where has this been tested?
Tested by retrieving the External Credential metadata and executing the sgd command.

---

**Operating System:** Windows

**yarn version:** 1.22.19

**node version:** v16.14.0

**git version:** git version 2.33.0.windows.2

**sfdx version:** sfdx-cli/7.175.0 win32-x64 node-v18.12.0

**sgd plugin version:** 5.7.1

### CODE REVIEW

**Review by scolladon — COMMENTED** [review]
LGTM

@nodex0 Could you check if the execution of `yarn increment:apiversion` provide a different result ? 
To do so:
```sh
$ rm -rf src/metadata/v56.json
$ yarn increment:apiversion
```

I tried locally and it is ok on my side, I just want to make sure it has the same output on your side as well.
Let us know the result and I'll approve the PR just after that

**Comment by scolladon** [comment]
@nodex0 I also think External Credential should be removed from v55.json
According to the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_externalcredential.htm?q=ExternalCredential) it is present only in v56

**Comment by nodex0** [comment]
Removed the metadata from v55, you're right, if it was officially defined I understand it should not be there for that API version. I was a little misdirected when retrieving it with API v55, I guess it is undocumented for some older API versions.

For the yarn increment:apiversion, I am unable to run it in my Windows machine probably due to environment issues (I'm trying in mingw bash).

**Comment by scolladon** [comment]
No problem for the v.55, you were probably in a preview sandbox or preview Devhub creating preview scratch org.
That's what code review are for 😃 

No problem for the `yarn` command as well, it is `unix` oriented.

**Review by scolladon — APPROVED** [review]
LGTM

Thanks for this awesome contribution, you went ahead of us and created the v56 version !

**Pull request merged**
