### PR TITLE
feat: add Expression Set metadatas support

### LINKED ISSUE #959: Expression Set Version and Context Definitions metadata support
### Discussed in https://github.com/scolladon/sfdx-git-delta/discussions/958

<div type='discussions-op-text'>

<sup>Originally posted by **PythSomeone** December  9, 2024</sup>
Hi,

When a delta is generated, changes or creations of the Expression Set Version and Context Definition are not shown in the resulting delta.

Could you please add support for both types of metadata?</div>

### PR DESCRIPTION
**Pull request by scolladon**
# Explain your changes

---

Support for :

[`ContextDefinition`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_contextdefinition.htm?q=Context%20Definitions)
[`ExpressionSetMessageToken`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_expressionsetmessagetoken.htm?q=ExpressionSetMessageToken)
[`ExpressionSetObjectAlias`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_expressionsetobjectalias.htm?q=ExpressionSetMessageToken)
[`ProductSpecificationType`](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationtype.htm)
[`ProductSpecificationRecType`](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationrectype.htm)
[`UiFormatSpecificationSet`](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_uiformatspecificationset.htm)
`ExpressionSetVersion` (not described in the metadata API documentation but available through it)

# Does this close any currently open issues?

---

closes #959

### CODE REVIEW

**Comment by scolladon** [comment]
Hi @PythSomeone !

Could you test on your side and help us validate this PR please ?
You can follow those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to easily do it on your side

**Comment by PythSomeone** [comment]
@scolladon 
Delta correctly recognized changes on ContextDefinition but failed to include the ExpressionSetDefinitionVersion

**Comment by scolladon** [comment]
> @scolladon Delta correctly recognized changes on ContextDefinition but failed to include the ExpressionSetDefinitionVersion

Do you have an example of `ExpressionSetDefinitionVersion` from the metadata please ?
I cannot find any reference to in the metadata api documentation. It seems to be included directly inside [ExpressionSetDefinition](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_expressionsetdefinition.htm#:~:text=template%20or%20not.-,versions,-Field%20Type) and [only available via the Tooling API](https://developer.salesforce.com/docs/atlas.en-us.industries_reference.meta/industries_reference/tooling_api_objects_expressionsetdefinitionversion.htm).

**Comment by scolladon** [comment]
FYI @PythSomeone: Product Catalog Management metadata have been added ([ProductSpecificationType](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationtype.htm) and [ProductSpecificationRecType](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationrectype.htm))

**Comment by scolladon** [comment]
Hi @PythSomeone !

Have you been able to look at my question [here](https://github.com/scolladon/sfdx-git-delta/pull/960#issuecomment-2531829893) ?
And also could you test the [Product Catalog Management metadata](https://github.com/scolladon/sfdx-git-delta/pull/960#issuecomment-2532089474) added in this PR and let me know please ?

**Comment by PythSomeone** [comment]
Hi @scolladon 
Here is the path for the metadata in question `force-app\main\default\expressionSetVersion\Product_Discovery_Pricing_Procedure_V1.expressionSetVersion-meta.xml`

As for ([ProductSpecificationType](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationtype.htm) and [ProductSpecificationRecType](https://developer.salesforce.com/docs/atlas.en-us.revenue_lifecycle_management_dev_guide.meta/revenue_lifecycle_management_dev_guide/sforce_api_objects_productspecificationrectype.htm)) - they are properly generated by Delta

**Comment by scolladon** [comment]
Hi @PythSomeone, thanks for your feedback and for the information.
`ExpressionSetVersion` has been added and is ready for testing here

Hi @eqtkram, `UiFormatSpecificationSet` has been added and is ready for testing as well.
Follow information from this [comment](https://github.com/scolladon/sfdx-git-delta/pull/960#issuecomment-2527431155) to test locally.

**Comment by PythSomeone** [comment]
@scolladon Looks like all the objects I concerned about are now correctly generated in delta. Thanks a lot!

**Pull request merged**
