### PR TITLE
fix: suffix based translation file detection and output subDir

### LINKED ISSUE #321: When a flow metadata is changed and the translations isn't, all the translations for the new flow version are lost
## What is the problem?

---

When we change a flow metadata and don't make any change to the translations file, after the deploy we loose all the translations related to that flow.
The reason for this is that the translation for each flow is managed by a flow version, so if a flow is deployed without the translation file, then there are no translations for its new version.

## Steps to reproduce

---

1. Have an env with a flow with translations
2. Use sgd to produce a package that detects a change only in the flow so a package.xml file is produced without the translations file
3. After the package is deployed, the new flow version will loose its translations

## Current workaround

---

Every time we touch a flow metadata, we make a small insignificant change to the translation file too so it will also be added to the package.xml

## Solution suggestion

If a flow was added to to the package.xml file and a translation wasn't, then force add translations.
This functionality might also be activated by a flag in the cli or some kind of configuration

a more advanced solution is to check which specific file translation contains a reference to that specific changed flow instead of adding the entire translations directory

### PR DESCRIPTION
**Pull request by scolladon**
# Explain your changes

---

Ensure the flow translation code deals with both `.translation` and `.translation-meta.xml` Translation files suffix.
Test if the translation file is a sub dir of the output folder when output folder is different than the repository folder

# Does this close any currently open issues?

---

closes #321 

- [x] Jest tests added to cover the fix.

### CODE REVIEW

**Comment by scolladon** [comment]
Hi @ArielS1 !

Could you test on your side and help us validate this PR please ?
You can follow those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to easily do it on your side

**Comment by ArielS1** [comment]
actually the file's extension on the real repo translation-meta.xml
but i'm still able to reproduce it both on dev-901 and 5.42.0
check my repository

**Comment by scolladon** [comment]
> actually the file's extension on the real repo translation-meta.xml but i'm still able to reproduce it both on dev-901 and 5.42.0 check my repository

on my side it is fixed with the version in this PR...
I mean the translation file is added in the package.xml and is is also copied in the output folder.

Are you sure you are using the version of the plugin from this PR ?

**Comment by ArielS1** [comment]
> > actually the file's extension on the real repo translation-meta.xml but i'm still able to reproduce it both on dev-901 and 5.42.0 check my repository
> 
> on my side it is fixed with the version in this PR... I mean the translation file is added in the package.xml and is is also copied in the output folder.
> 
> Are you sure you are using the version of the plugin from this PR ?

did you pull my last changes in my repo?
this is what i do, and the generated package.xml is like in the repo.

arielsi@Ariel:/mnt/c/Users/arielsi/IdeaProjects/SgdFlowTranslations$ sfdx plugins:install sfdx-git-delta@dev-901
 ›   Warning: sfdx-cli update available from 7.172.0 to 7.209.6.
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
warning "sfdx-git-delta > @salesforce/command > @oclif/test > @oclif/core > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
warning "sfdx-git-delta > @salesforce/command > @oclif/test > @oclif/core > ts-node@10.9.2" has unmet peer dependency "typescript@>=2.7".
Installing plugin sfdx-git-delta... installed v5.42.0-dev-901.10410862637-1
arielsi@Ariel:/mnt/c/Users/arielsi/IdeaProjects/SgdFlowTranslations$ sfdx plugins
 ›   Warning: sfdx-cli update available from 7.172.0 to 7.209.6.
sfdx-git-delta 5.42.0-dev-901.10410862637-1 (dev-901)
arielsi@Ariel:/mnt/c/Users/arielsi/IdeaProjects/SgdFlowTranslations$ sfdx sgd:source:delta --to master --from changeFlow --repo . --output .
 ›   Warning: sfdx-cli update available from 7.172.0 to 7.209.6.
(node:670) Warning: Deprecated environment variable: SFDX_AUTOUPDATE_DISABLE. Please use SF_AUTOUPDATE_DISABLE instead.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:670) Warning: Deprecated environment variable: SFDX_DISABLE_AUTOUPDATE. Please use SF_DISABLE_AUTOUPDATE instead.
(node:670) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": []
}

**Comment by scolladon** [comment]
> did you pull my last changes in my repo? this is what i do, and the generated package.xml is like in the repo.

Yep @ArielS1, I created a new repository and tried with the version of this PR.
The issue you have that I don't is for you the output folder is the current folder.
The plugin check for the translations file that are not in the output folder because when using `-d` file are copied and it should not evaluate the file generated by the plugin. In your scenario the output folder is the repository folder so translation files are ignored.
You should use a dedicated folder for the output of the plugin and avoid using the same folder as the repository because using `-d` would override in file metadata (like workflow, custom labels, etc).

You can workaround this issue by creating a folder `output` and pass this folder to the parameter `--output` :
```sh 
mkdir output
sfdx sgd:source:delta --to master --from changeFlow --repo . -o output
```

I'll ship a fix in this PR to ignore the "output folder filter" when `--output` is equal to `--repo`

**Comment by scolladon** [comment]
I fixed the issue when output is equal to the repo, could you QA one more time and let me know your finding please @ArielS1 ?

**Comment by scolladon** [comment]
> I fixed the issue when output is equal to the repo, could you QA one more time and let me know your finding please @ArielS1 ?

Hi @ArielS1 😁 do you think you could have a final round of UAT (hopefully) please ?

**Comment by ArielS1** [comment]
> > I fixed the issue when output is equal to the repo, could you QA one more time and let me know your finding please @ArielS1 ?
> 
> Hi @ArielS1 😁 do you think you could have a final round of UAT (hopefully) please ?

Hi,

I checked and it works both on my local env and on the real build env.

Thanks

**Pull request merged**
