### PR TITLE
feat: add API v58 support

### PR DESCRIPTION
**Pull request by scolladon**
# Explain your changes

---

add API v58 metadata definition

### CODE REVIEW

**Review by mehdisfdc — APPROVED** [review]

**Comment by jonny-harte** [comment]
hi @scolladon when will this be the stable version?

**Comment by scolladon** [comment]
Hi @jonny-harte, we'll move the latest and stable version to the latest version containing the v58 api today or tomorrow

**Comment by Raspikabek** [comment]
Hey @scolladon , where are these json file definitions for metadata types coming from? I mean, is there any Salesforce documentation about this list of files? 

For context: I'm building a plugin myself and I need something similar to identify the metadata type name, directory file and if contains child elements like CustomObjects that contains CustomField.

(apologies this might not be the right place, but didn't see fair to raise an 'issue' for this.)

**Comment by scolladon** [comment]
Hi @Raspikabek !

Those json files have been generated long time ago from the metadata wsdl if I remember correctly. We converted it from xml to json and then rework the format a bit so it is easier to consume.

But today there is another way to do it, much more easier. We have plan to refactor the plugin to use it.
It is the [Metadata Registry](https://github.com/forcedotcom/source-deploy-retrieve/blob/main/HANDBOOK.md#metadata-registry), if you need to have metadata definition in your plugin I think you should consider using this library.

I'll be happy to discuss design with you for your new plugin ! Contact me on [linkedin](https://www.linkedin.com/in/sebastien-colladon/)

**Pull request merged**
