### PR TITLE
refactor: create git adapter

### PR DESCRIPTION
**Pull request by scolladon**
# Explain your changes

---

Create a git adapter layer
Implement most of the git methods with `isomorphic-git` and some that were not available with `simple-git`

### CODE REVIEW

**Comment by scolladon** [comment]
I put it back on draft because it does not behave well for very large repository (10x worst in performance)

**Comment by scolladon** [comment]
When this [PR](https://github.com/isomorphic-git/isomorphic-git/pull/1853) will be merged on `isomorphic-git` side, the performance will be fixed and we will be able to merge this PR

**Comment by scolladon** [comment]
The performance improvement has been included, we can now review this PR

**Comment by scolladon** [comment]
Hi @hsaraujo !

Long time no see since your contribution [here](https://github.com/scolladon/sfdx-git-delta/pull/353) 😄 

Could you help us here to test this refactoring ?
I would like to be sure the new implementation stills work with git submodule from your perspective.

I don't know if you remember, you can follow those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to test locally a specific branch

I hope you'll be able to help here

**Comment by hsaraujo** [comment]
Sure can @scolladon! I'm on leave until the end of the month. Will pick this up when I'm back home.

**Review by mehdisfdc — DISMISSED** [review]
@scolladon  As discussed, let's include this one (and #750 ) in a release candidate, to make it easier to test it extensively 😃

**Review by mehdisfdc — DISMISSED** [review]

**Review by mehdisfdc — APPROVED** [review]

**Comment by scolladon** [comment]
Hi @hsaraujo,

We shipped this branch in the `latest-rc` channel but not yet in the `latest` channel.
We want to wait for feedback in order make it available massively.

Could you try it and let us know please ?

**Comment by jjulicher** [comment]
@scolladon  Thanks for this! Just got a bit of breathing space at work - so have integrated this into our ADO pipeline. Looking good so far - have noticed there is about a 300% speed improvement when generating the diff as well.

**Comment by scolladon** [comment]
You're welcome @jjulicher !
Have you been able to test [this](https://github.com/scolladon/sfdx-git-delta/pull/750) one two ?
It brings one of your [suggestions](https://github.com/scolladon/sfdx-git-delta/issues/642)

**Comment by jjulicher** [comment]
Haha. I posted on the wrong one issue. Yes the other one.

Thanks

**Pull request merged**
