### PR TITLE
feat: add FeatureParameter metadata support

### PR DESCRIPTION
**Pull request by aljaz823**
# Explain your changes

---

Add metadata support for all three types of Feature Parameters:
- [FeatureParameterBoolean](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_featureparameterboolean.htm)
- [FeatureParameterDate](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_featureparameterdate.htm)
- [FeatureParameterInteger](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_featureparameterinteger.htm)

### CODE REVIEW

**Review by scolladon — CHANGES_REQUESTED** [review]
Nice addition, thanks !!!

Could the definition be at the top of the file ?
Also, has it been tested manually ?

**Comment by aljaz823** [comment]
> Nice addition, thanks !!!
> 
> Could the definition be at the top of the file ? Also, has it been tested manually ?

Sure, I moved definitions to the top of metadata files.
It has been tested manually, here is the result:
image

Generated diff package.xml file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>FeatureBoolean1</members>
        <name>FeatureParameterBoolean</name>
    </types>
    <types>
        <members>FeatureDate1</members>
        <name>FeatureParameterDate</name>
    </types>
    <types>
        <members>FeatureSet1</members>
        <members>FeatureSet2</members>
        <name>FeatureParameterInteger</name>
    </types>
    <version>60.0</version>
</Package>
```

**Review by scolladon — COMMENTED** [review]
Thanks for putting the definition on top of the file.
The bottom is reserved to certain types I prefer to be grouped.

Could you add an [integration test](https://github.com/scolladon/sfdx-git-delta/blob/main/__tests__/integration/services.test.ts) for those types please ?
You just have to add an item in the list for each new type.
If you struggle with that I can add it, just let me know
As they are regrouped in the same folder I would like to couple the test with the metadata definition, just to fix the spec explicitely

**Comment by aljaz823** [comment]
I added the integration tests, though I'm not familiar with that so I just followed other patterns. Let me know if it needs additional fixing.

**Review by scolladon — APPROVED** [review]
LGTM

Great job, thanks for this contribution

**Pull request merged**
