### PR TITLE
fix: git compatibility issue with large repository on windows

### LINKED ISSUE #862: Getting `Could not find` error when generating delta source
Issue verification check:

- [X] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---
We are getting an error when trying to generate delta source with sfdx-git-delta versions above 5.34.0. 

### What is the parameter and the value you used with it?
sgd source delta --to HEAD --from stash/master --source C:\<REPO_PATH> --api-version 59.0 --output C:\<REPO_PATH>\delta-src/ --generate-delta

### What is the expected result?
Delta source generation succeeds.

### What is the actual result?
Delta source generation fails. 
Json Response:
{"success":false,"error":"Could not find b2c43ed8d669af3b0af194a54362238c0ed66de5.","output":"C:\\<REPO_PATH>\\delta-src/","warnings":[]}

## Steps to reproduce
---
We are unable to reproduce the issue locally (within our machines) the issue is occurring within our build servers.
## Execution context
---
Within our build servers we use Bamboo and Windows 2012.
**Operating System:** Windows 2012

**yarn version:** N/A

**node version:** v18.12.0

**git version:** git version 2.29.2.windows.3

**sfdx version:** @salesforce/cli/2.40.7 win32-x64 node-v20.12.2

**sgd plugin version:** sfdx-git-delta 5.39.2 (5.39.2)

### PR DESCRIPTION
**Pull request by scolladon**
# Explain your changes

---

Implements Git Adapter using only `simpleGit`
Remove implementation using `isomorphic-git` and simplify treatment

Implementation is now a little bit simpler
But it is also slower and more dependant of git behavior in the terminal

# Does this close any currently open issues?

---

closes #862 

- [x] Jest tests added to cover the fix.

### CODE REVIEW

**Comment by scolladon** [comment]
Hi @kez-sophos @ALesc21 @dsweetmanusda @ !

Could you test on your side and help us validate this PR please ?
You can follow those [steps](https://github.com/scolladon/sfdx-git-delta/blob/main/CONTRIBUTING.md#testing-the-plugin-from-a-pull-request) to easily do it on your side

**Comment by scolladon** [comment]
### Performance test

#### Current Pull request (`simplegit` git adapter)

e2e-test x 0.69 ops/sec ±7.74% (6 runs sampled)
e2e-test x 0.68 ops/sec ±6.30% (6 runs sampled)
e2e-test x 0.68 ops/sec ±4.39% (6 runs sampled)
e2e-test x 0.69 ops/sec ±4.35% (6 runs sampled)
e2e-test x 0.70 ops/sec ±2.67% (6 runs sampled)

#### Current main `v5.49.2` (`isomorphic-git` git adapter)

e2e-test x 0.73 ops/sec ±16.35% (6 runs sampled)
e2e-test x 0.79 ops/sec ±13.19% (7 runs sampled)
e2e-test x 0.88 ops/sec ±2.68% (7 runs sampled)
e2e-test x 0.90 ops/sec ±1.62% (7 runs sampled)
e2e-test x 0.87 ops/sec ±3.07% (7 runs sampled)

**Comment by ALesc21** [comment]
hi @scolladon,

after the installation of the new version I run the delta command and could build successfully a package with the latest api version.
So for us the fix is working on the server now. Great job ;)


```
$ sf sgd:source:delta --to HEAD --from HEAD^ --output deployment/ONECRM-0002
 »   Warning: @salesforce/cli update available from 2.62.6 to 2.64.8.
(node:12296) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instea
d.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:12296) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
{
  "error": null,
  "output": "deployment/ONECRM-0002",
  "success": true,
  "warnings": [
    "[INFORMATION] sfdx-git-delta v6 is coming soon! Read more and plan your migration: https://github.com/scolladon/sfd
x-git-delta/issues/936"
  ]
}
```

**Comment by scolladon** [comment]
Thank you very much for your contribution @ALesc21 
I just wrote an optimised version, could you repeat the test from the start and tell me the result on your side please ? (reinstall the save dev package and rerun your command please)

Feel free to contribute as well @kez-sophos & @dsweetmanusda ! Your feedback will be really valuable and I hope it will fix your situation as well.

**Comment by ALesc21** [comment]
hi @scolladon, I reinstalled the version and tested it again. It is still working with your fix for me on the windows server. Below you can find the steps (install dev version, check plugin, generate the package) 

```
DEBIE1TC_SFDX@MSE-SVCRM01 MINGW64 /c/BuildAgent01/work/86775e496ec9c505 (feature/ONECRM-8856|SPARSE)
$ sfdx plugins:install sfdx-git-delta@dev-947
 »   Warning: @salesforce/cli update available from 2.62.6 to 2.64.8.
(node:11880) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instea
d.
(Use `node --trace-deprecation ...` to show where the warning was created)
? sfdx-git-delta isn't signed by Salesforce. Only install the plugin if you trust its creator. Do you want to continue
the installation? yes
Because you approved this plugin, you can avoid future installation confirmations by adding the plugin to the unsignedPl
uginAllowList.json file. For details, see https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/s
fdx_setup_allowlist.htm.
Finished digital signature check.
removed 11 packages, and changed 1 package in 2s
@salesforce/cli: Installing plugin sfdx-git-delta@dev-947... installed v5.49.2

DEBIE1TC_SFDX@MSE-SVCRM01 MINGW64 /c/BuildAgent01/work/86775e496ec9c505 (feature/ONECRM-8856|SPARSE)
$ sf plugins --core
 »   Warning: @salesforce/cli update available from 2.62.6 to 2.64.8.
(node:6060) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead
.
(Use `node --trace-deprecation ...` to show where the warning was created)
@oclif/plugin-autocomplete 3.2.5 (core)
@oclif/plugin-commands 4.1.3 (core)
@oclif/plugin-help 6.2.14 (core)
@oclif/plugin-not-found 3.2.22 (core)
@oclif/plugin-plugins 5.4.14 (core)
@oclif/plugin-search 1.2.11 (core)
@oclif/plugin-update 4.6.3 (core)
@oclif/plugin-version 2.2.14 (core)
@oclif/plugin-warn-if-update-available 3.1.18 (core)
@oclif/plugin-which 3.2.15 (core)
apex 3.5.1 (core)
api 1.3.1 (core)
auth 3.6.65 (core)
community 3.0.14 (3.0.14)
data 3.7.0 (core)
deploy-retrieve 3.12.17 (core)
info 3.4.9 (core)
limits 3.3.32 (core)
marketplace 1.2.26 (core)
org 4.6.0 (core)
packaging 2.8.11 (core)
schema 3.3.34 (core)
settings 2.3.23 (core)
sfdx-git-delta 5.49.2-dev-947.11779231727-1 (dev-947)
sobject 1.4.41 (core)
source 3.5.21 (core)
telemetry 3.6.15 (core)
templates 56.3.22 (core)
trust 3.7.33 (core)
user 3.5.32 (core)

Uninstalled JIT Plugins:
custom-metadata 3.3.33
dev 2.4.2
devops-center 1.2.24
env 3.0.33
functions 1.23.0
signups 2.5.21
@salesforce/sfdx-plugin-lwc-test 1.2.1
@salesforce/sfdx-scanner 4.6.0

DEBIE1TC_SFDX@MSE-SVCRM01 MINGW64 /c/BuildAgent01/work/86775e496ec9c505 (feature/ONECRM-8856|SPARSE)
$ sf sgd:source:delta --to HEAD --from HEAD^ --output deployment/ONECRM-0002
 »   Warning: @salesforce/cli update available from 2.62.6 to 2.64.8.
(node:6920) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead
.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:6920) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
{
  "error": null,
  "output": "deployment/ONECRM-0002",
  "success": true,
  "warnings": [
    "[INFORMATION] sfdx-git-delta v6 is coming soon! Read more and plan your migration: https://github.com/scolladon/sfd
x-git-delta/issues/936"
  ]
}

```

**Review by mehdicherf — APPROVED** [review]

**Comment by ALesc21** [comment]
the version 5.49.3 is already installed and running smoothly on the server. 
I really appreciate your help and hard work ;)

**Pull request merged**
